const locationData = {
    "BARISHAL": {
        "BARGUNA": ["AMTALI","BAMNA","BARGUNA SADAR","BETAGI","PATHARGHATA","TALTALI"],
  
        "BARISAL": ["AGAILJHARA","BABUGANJ","BAKERGANJ","BANARI PARA","GAURNADI","HIZLA","BARISAL SADAR","MHENDIGANJ","MULADI","WAZIRPUR"],
  
        "BHOLA": ["BHOLA SADAR","BURHANUDDIN","CHAR FASSON","DAULAT KHAN","LALMOHAN","MANPURA","TAZUMUDDIN"],
  
        "JHALOKATI": ["JHALOKATI SADAR","KANTHALIA","NALCHITY","RAJAPUR"],
  
        "PATUAKHALI": ["BAUPHAL","DASHMINA","DUMKI","GALACHIPA","KALAPARA","MIRZAGANJ","PATUAKHALI SADAR","RANGABALI"],
  
        "PIROJPUR": ["BHANDARIA","KAWKHALI","MATHBARIA","NAZIRPUR","PIROJPUR SADAR","NESARABAD (SWARUPKATI)","ZIANAGAR"],
  
    },
    
    "CHATTOGRAM": {
        "BANDARBAN": ["ALIKADAM","BANDARBAN SADAR","LAMA","NAIKHONGCHHARI","ROWANGCHHARI","RUMA","THANCHI"],
  
        "BRAHMANBARIA": ["AKHAURA","BANCHHARAMPUR","BIJOYNAGAR","BRAHMANBARIA SADAR","ASHUGANJ","KASBA","NABINAGAR","NASIRNAGAR","SARAIL"],
  
        "CHANDPUR": ["CHANDPUR SADAR","FARIDGANJ","HAIM CHAR","HAJIGANJ","KACHUA","MATLAB DAKSHIN","MATLAB UTTAR","SHAHRASTI"],
  
        "CHITTAGONG":["ANOWARA","BAYEJID BOSTAMI","BANSHKHALI","BAKALIA","BOALKHALI","CHANDANAISH","CHANDGAON","CHITTAGONG PORT","DOUBLE MOORING","FATIKCHHARI","HALISHAHAR","HATHAZARI","KOTWALI","KHULSHI","LOHAGARA","MIRSHARAI","PAHARTALI","PANCHLAISH","PATIYA","PATENGA","RANGUNIA","RAOZAN","SANDWIP","SATKANIA","SITAKUNDA"],
  
         
        "COMILLA": ["BARURA","BRAHMAN PARA","BURICHANG","CHANDINA","CHAUDDAGRAM","COMILLA SADAR DAKSHIN","DAUDKANDI","DEBIDWAR","HOMNA","COMILLA ADARSHA SADAR","LAKSAM","MANOHARGANJ","MEGHNA","MURADNAGAR","NANGALKOT","TITAS"],
  
        "COX'S BAZAR":["CHAKARIA","COX'S BAZAR SADAR","KUTUBDIA","MAHESHKHALI","PEKUA","RAMU","TEKNAF","UKHIA"],
        
        "FENI":["CHHAGALNAIYA","DAGANBHUIYAN","FENI SADAR","FULGAZI","PARSHURAM","SONAGAZI"],
  
        "KHAGRACHHARI":["DIGHINALA","KHAGRACHHARI SADAR","LAKSHMICHHARI","MAHALCHHARI","MANIKCHHARI","MATIRANGA","PANCHHARI","RAMGARH"],
  
        "LAKSHMIPUR":["KAMALNAGAR","LAKSHMIPUR SADAR","ROYPUR","RAMGANJ","RAMGATI"],
  
        "NOAKHALI":["BEGUMGANJ","CHATKHIL","COMPANIGANJ","HATIYA","KABIRHAT","SENBAGH","SONAIMURI","SUBARNACHAR","NOAKHALI SADAR"],
  
        "RANGAMATI":["BAGHAICHHARI","BARKA","KAWKHALI (BETBUNIA)","BELAI CHHARI","KAPTAI","JURAI CHHARI","LANGADU","NANIARCHAR","RAJASTHALI","RANGAMATI SADAR"],
  
  
    },
    "DHAKA": {
        "DHAKA": ["ADABOR"," BADDA","BANGSHAL","BIMAN BANDAR","BANANI","CANTONMENT","CHAK BAZAR","DAKSHINKHAN","DARUS SALAM","DEMRA","DHAMRAI","DHANMONDI","DOHAR","BHASAN TEK","BHATARA","GENDARIA","GULSHAN","HAZARIBAGH","JATRABARI","KAFRUL","KADAMTALI","KALABAGAN","KAMRANGIR CHAR","KHILGAON","KHILKHET","KERANIGANJ","KOTWALI","LALBAGH","MIRPUR","MOHAMMADPUR","MOTIJHEEL","MUGDA PARA","NAWABGANJ","NEW MARKET","PALLABI","PALTAN","RAMNA","RAMPURA","SABUJBAGH","RUPNAGAR","SAVAR","SHAHJAHANPUR","SHAH ALI","SHAHBAGH","SHYAMPUR","SHER-E-BANGLA NAGAR","SUTRAPUR","TEJGAON","TEJGAON IND. AREA","TURAG","UTTARA  PASCHIM","UTTARA  PURBA","UTTAR KHAN","WARI"],
         
        "FARIDPUR":["ALFADANGA","BHANGA","BOALMARI","CHAR BHADRASAN","FARIDPUR SADAR","MADHUKHALI","NAGARKANDA","SADARPUR","SALTHA"],
  
        "GAZIPUR": ["GAZIPUR SADAR","KALIAKAIR","KALIGANJ","KAPASIA","SREEPUR"],
        
        "GOPALGANJ":["GOPALGANJ SADAR","KASHIANI","KOTALIPARA","MUKSUDPUR","TUNGIPARA"],
  
        
        "KISHOREGONJ":["AUSTAGRAM","BAJITPUR","BHAIRAB","HOSSAINPUR","ITNA","KARIMGANJ","KATIADI","KISHOREGANJ SADAR","KULIAR CHAR","MITHAMAIN","NIKLI","PAKUNDIA","TARAIL"],
         
        "MADARIPUR":["KALKINI","MADARIPUR SADAR","RAJOIR","SHIBCHAR"],
  
        "MANIKGANJ":["DAULATPUR","GHIOR","HARIRAMPUR","MANIKGANJ SADAR","SATURIA","SHIBALAYA","SINGAIR"],
  
        "MUNSHIGANJ":["GAZARIA","LOHAJANG","MUNSHIGANJ SADAR","SERAJDIKHAN","SREENAGAR","TONGIBARI"],
  
  
        "NARAYANGANJ": ["ARAIHAZAR","SONARGAON","BANDAR","NARAYANGANJ SADAR","RUPGANJ"],
         
        "NARSINGDI":["BELABO","MANOHARDI","NARSINGDI SADAR","PALASH","ROYPURA","SHIBPUR"],
  
        "RAJBARI": ["BALIAKANDI","GOALANDA","KALUKHALI","PANGSHA","RAJBARI SADAR"],
        
        "SHARIATPUR": ["BHEDARGANJ","DAMUDYA","GOSAIRHAT","NARIA","SHARIATPUR SADAR","ZANJIRA"],
  
        "TANGAIL": ["BASAIL","BHUAPUR","DELDUAR","DHANBARI","GHATAIL","GOPALPUR","KALIHATI","MADHUPUR","MIRZAPUR","NAGARPUR","SAKHIPUR","TANGAIL SADAR"],
    },
    
    "KHULNA": {
        "BAGERHAT":["BAGERHAT SADAR","CHITALMARI","FAKIRHAT","KACHUA","MOLLAHAT","MONGLA","MORRELGANJ","RAMPAL","SARANKHOLA"],
  
        "CHUADANGA":["ALAMDANGA","CHUADANGA SADAR","DAMURHUDA","JIBAN NAGAR"],
  
        "JESSORE":["ABHAYNAGAR","BAGHER PARA","CHAUGACHHA","JHIKARGACHHA","KESHABPUR","JESSORE SADAR","MANIRAMPUR","SHARSHA"],
  
        "JHENAIDAH":["HARINAKUNDA","JHENAIDAH SADAR","KALIGANJ","KOTCHANDPUR","MAHESHPUR","SHAILKUPA"],
  
        "KHULNA":["BATIAGHATA","DACOPE","DAULATPUR","DUMURIA","DIGHALIA","KHALISHPUR","KHAN JAHAN ALI","KHULNA SADAR","KOYRA","PAIKGACHHA","PHULTALA","RUPSA","SONADANGA","TEROKHADA"],
  
        "KUSHTIA":["BHERAMARA","DAULATPUR","KHOKSA","KUMARKHALI","KUSHTIA SADAR","MIRPUR"],
  
        "MAGURA":["MAGURA SADAR","MOHAMMADPUR","SHALIKHA","SREEPUR"],
  
        "MEHERPUR":["GANGNI","MUJIB NAGAR","MEHERPUR SADAR"],
  
        "NARAIL":["KALIA","LOHAGARA","NARAIL SADAR"],
  
        "SATKHIRA":["ASSASUNI","DEBHATA","KALAROA","KALIGANJ","SATKHIRA SADAR","SHYAMNAGAR","TALA"],
  
  
    },
    
    "MYMENSINGH": {
        "MYMENSINGH":["BHALUKA","DHOBAURA","FULBARIA","GAFFARGAON","GAURIPUR","HALUAGHAT","ISHWARGANJ","MYMENSINGH SADAR","MUKTAGACHHA","NANDAIL","PHULPUR","TRISHAL"],
  
        "JAMALPUR":["BAKSHIGANJ","DEWANGANJ","ISLAMPUR","JAMALPUR SADAR","MADARGANJ","MELANDAHA","SARISHABARI"],
  
        "NETRAKONA": ["ATPARA","BARHATTA","DURGAPUR","KHALIAJURI","KALMAKANDA","KENDUA","MADAN","MOHANGANJ","NETROKONA SADAR","PURBADHALA"],
  
        "SHERPUR": ["JHENAIGATI","NAKLA","NALITABARI","SHERPUR SADAR","SREEBARDI"],
    },
    "RAJSHAHI": {
       "BOGRA":["ADAMDIGHI","BOGRA SADAR","DHUNAT","DHUPCHANCHIA","GABTALI","KAHALOO","NANDIGRAM","SARIAKANDI","SHAJAHANPUR","SHERPUR","SHIBGANJ","SONATOLA"],
  
       "JOYPURHAT":["AKKELPUR","JOYPURHAT SADAR","KALAI","KHETLAL","PANCHBIBI"],
  
       "NAOGAON":["ATRAI","BADALGACHHI","DHAMOIRHAT","MANDA","MAHADEBPUR","NAOGAON SADAR","NIAMATPUR","PATNITALA","PORSHA","RANINAGAR","SAPAHAR"],
  
       "NATORE":["BAGATIPARA","BARAIGRAM","GURUDASPUR","LALPUR","NATORE SADAR","SINGRA"],
  
       "CHAPAI NABABGANJ":["BHOLAHAT","GOMASTAPUR","NACHOLE","CHAPAI NABABGANJ SADAR","SHIBGANJ"],
  
       "PABNA":["ATGHARIA","BERA","BHANGURA","CHATMOHAR","FARIDPUR","ISHWARDI","PABNA SADAR","SANTHIA","SUJANAGAR"],
  
       "RAJSHAHI":["BAGHA","BAGHMARA","BOALIA","CHARGHAT","DURGAPUR","GODAGARI","MATIHAR","MOHANPUR","PABA","PUTHIA","RAJPARA","SHAH MAKHDUM","TANORE"],
  
       "SIRAJGANJ":["BELKUCHI","CHAUHALI","KAMARKHANDA","KAZIPUR","ROYGANJ","SHAHJADPUR","SIRAJGANJ SADAR","TARASH","ULLAH PARA"],
  
    },
  
    "RANGPUR": {
       "DINAJPUR":["BIRAMPUR","BIRGANJ","BIRAL","BOCHAGANJ","CHIRIRBANDAR","FULBARI","GHORAGHAT","HAKIMPUR","KAHAROLE","KHANSAMA","DINAJPUR SADAR","NAWABGANJ","PARBATIPUR"],
  
       "GAIBANDHA":["FULCHHARI","GAIBANDHA SADAR","GOBINDAGANJ","PALASHBARI","SADULLAPUR","SAGHATA","SUNDARGANJ"],
  
       "KURIGRAM":["BHURUNGAMARI","CHAR RAJIBPUR","CHILMARI","PHULBARI","KURIGRAM SADAR","NAGESHWARI","RAJARHAT","RAUMARI","ULIPUR"],
  
       "LALMONIRHAT":["ADITMARI","HATIBANDHA","KALIGANJ","LALMONIRHAT SADAR","PATGRAM"],
  
       "NILPHAMARI":["DIMLA","DOMAR","JALDHAKA","KISHOREGANJ","NILPHAMARI SADAR","SAIDPUR"],
  
       "PANCHAGARH":["ATWARI","BODA","DEBIGANJ","PANCHAGARH SADAR","TENTULIA"],
  
       "RANGPUR":["BADARGANJ","GANGACHARA","KAUNIA","RANGPUR SADAR","MITHA PUKUR","PIRGACHHA","PIRGANJ","TARAGANJ"],
  
       "THAKURGAON":["BALIADANGI","HARIPUR","PIRGANJ","RANISANKAIL","THAKURGAON SADAR"]
       
    },
    "SYLHET":{
        "HABIGANJ":["AJMIRIGANJ","BAHUBAL","BANIACHONG","CHUNARUGHAT","HABIGANJ SADAR","LAKHAI","MADHABPUR","NABIGANJ"],
  
        "MAULVIBAZAR":["BARLEKHA","JURI","KAMALGANJ","KULAURA","MAULVIBAZAR SADAR","RAJNAGAR","SREEMANGAL"],
  
        "SUNAMGANJ":["BISHWAMBARPUR","CHHATAK","DAKSHIN SUNAMGANJ","DERAI","DHARAMPASHA","DOWARABAZAR","JAGANNATHPUR","JAMALGANJ","SULLA","SUNAMGANJ SADAR","TAHIRPUR"],
  
        "SYLHET":["BALAGANJ","BEANI BAZAR","BISHWANATH","COMPANIGANJ","DAKSHIN SURMA","FENCHUGANJ","GOLAPGANJ","GOWAINGHAT","JAINTIAPUR","KANAIGHAT","SYLHET SADAR","ZAKIGANJ"],
  
    }
    
  };

  document.getElementById("division").addEventListener("change", populateDistricts);

  // Event listener for District dropdown to populate Thanas
  document.getElementById("district").addEventListener("change", populateThanas);
function populateDistricts() {
    const divisionSelect = document.getElementById("division");
    const districtSelect = document.getElementById("district");
    const thanaSelect = document.getElementById("thana");

    districtSelect.innerHTML = '<option value="" disabled selected>Select District</option>';
    thanaSelect.innerHTML = '<option value="" disabled selected>Select Upazila</option>';

    const selectedDivision = divisionSelect.value;
    if (selectedDivision) {
        const districts = Object.keys(locationData[selectedDivision]);
        districts.forEach(district => {
            const option = document.createElement("option");
            option.value = district;
            option.text = district;
            districtSelect.add(option);
        });
    }
}

function populateThanas() {
    const divisionSelect = document.getElementById("division");
    const districtSelect = document.getElementById("district");
    const thanaSelect = document.getElementById("thana");

    thanaSelect.innerHTML = '<option value="" disabled selected>Select Upazila</option>';

    const selectedDivision = divisionSelect.value;
    const selectedDistrict = districtSelect.value;
    if (selectedDivision && selectedDistrict) {
        const thanas = locationData[selectedDivision][selectedDistrict];
        thanas.forEach(thana => {
            const option = document.createElement("option");
            option.value = thana;
            option.text = thana;
            thanaSelect.add(option);
        });
    }
}


const search_form=document.getElementById("search-form")

search_form.addEventListener('submit', function(event){
    event.preventDefault()
    const form=event.target
    const payload=new FormData(form)
    fetch_api(payload)
})

const fetch_api=async (payload)=>{
    const res=await fetch(`http://127.0.0.1:5000/search-user`,{
        method:"POST",
        body:payload
    })
    val=await res.json()
    if(val["message"]=== "Successfull"){
        console.log(val["data"])
        data=JSON.stringify(val["data"])
        console.log(data)
        localStorage.setItem("donors_info",data)
        console.log(JSON.parse(localStorage.getItem("donors_info")))
        window.location.href="../HTML/show_donors.html"
    }
    else {
        alert("There is no donors")
    }
}

